### PR TITLE
Add configuration options for OodleImplementation and change the default to Oodle TCP

### PR DESCRIPTION
**Pull request by MapleHinata**
Very cool Square Enix, let's see if this sticks, this time around.

### CODE REVIEW

**Comment by MapleHinata** [comment]
This didn't get roll-backed today, so it's maybe fine?

**Comment by takhlaq** [comment]
maybe make this a configuration option, with corresponding drop down menu item? seems SE change their mind about this every so often

**Comment by MapleHinata** [comment]
> maybe make this a configuration option, with corresponding drop down menu item? seems SE change their mind about this every so often

Fair point, will do it later today.

**Comment by MapleHinata** [comment]
@takhlaq I added configuration options and context menu items for the Implementation type and a (optional) path to a shared Oodle library.
Should be fine to merge now?

**Review by takhlaq — APPROVED** [review]

**Pull request merged**
